name: Deploy to Azure Container Registry

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute unit tests
        run: |
          ./gradlew test 

      - name: Generate jar
        run: |
          ./gradlew bootJar 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get key vault secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "diploma-project"
          secrets: 'REGISTRY-USERNAME, REGISTRY-PASSWORD'
        id: myGetSecretAction

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: itstep.azurecr.io
          username: ${{ steps.myGetSecretAction.outputs.REGISTRY-USERNAME }}
          password: ${{ steps.myGetSecretAction.outputs.REGISTRY-PASSWORD }}
          
      - name: Build and push Docker images with docker compose
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
          
      - name: Create db container
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az container create \
                --name db \
                --resource-group my-resource \
                --image itstep.azurecr.io/db:latest \
                --cpu 1 --memory 1.0 \
                --ports 5432 \
                --registry-username ${{ steps.myGetSecretAction.outputs.REGISTRY-USERNAME }} \
                --registry-password ${{ steps.myGetSecretAction.outputs.REGISTRY-PASSWORD }} \
                --os-type Linux \
                --environment-variables \
                  POSTGRES_DB=${{ vars.POSTGRES_DB }} \
                  POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
                  POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
                --ip-address public \
                --dns-name-label database

      - name: Create app container
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az container create \
                --name app \
                --resource-group my-resource \
                --image itstep.azurecr.io/app:latest \
                --cpu 1 --memory 1.0 \
                --ports 8080 \
                --registry-username ${{ steps.myGetSecretAction.outputs.REGISTRY-USERNAME }} \
                --registry-password ${{ steps.myGetSecretAction.outputs.REGISTRY-PASSWORD }} \
                --os-type Linux \
                --environment-variables \
                  AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} \
                  AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }} \
                  AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }} \
                  SPRING_DATASOURCE_URL=${{ vars.DATASOURCE_URL }} \
                  SPRING_DATASOURCE_USERNAME=${{ secrets.POSTGRES_USER }} \
                  SPRING_DATASOURCE_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
                --ip-address public \
                --dns-name-label application
